// Mock data for UI development — replace with real API calls later

export const mockCategories = [
  { id: 1, name: "Laptops", slug: "laptops", icon: "💻", count: 48 },
  { id: 2, name: "Desktops", slug: "desktops", icon: "🖥️", count: 32 },
  { id: 3, name: "Monitors", slug: "monitors", icon: "🖱️", count: 25 },
  { id: 4, name: "Keyboards", slug: "keyboards", icon: "⌨️", count: 41 },
  { id: 5, name: "Gaming Gear", slug: "gaming-gear", icon: "🎮", count: 63 },
  { id: 6, name: "Storage", slug: "storage", icon: "💾", count: 29 },
  { id: 7, name: "Networking", slug: "networking", icon: "📡", count: 18 },
  { id: 8, name: "Accessories", slug: "accessories", icon: "🔌", count: 87 },
];

export const mockProducts = [
  {
    id: 1,
    name: "ASUS ROG Zephyrus G14",
    slug: "asus-rog-zephyrus-g14",
    price: 1299.99,
    sale_price: 1099.99,
    rating: 4.8,
    reviews: 234,
    image: "https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=400&q=80",
    category: "Laptops",
    brand: "ASUS",
    badge: "HOT",
    in_stock: true,
    is_featured: true,
  },
  {
    id: 2,
    name: "MacBook Pro 14\" M3 Pro",
    slug: "macbook-pro-14-m3",
    price: 1999.99,
    sale_price: null,
    rating: 4.9,
    reviews: 512,
    image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=400&q=80",
    category: "Laptops",
    brand: "Apple",
    badge: "NEW",
    in_stock: true,
    is_featured: true,
  },
  {
    id: 3,
    name: "Dell XPS 15 OLED",
    slug: "dell-xps-15-oled",
    price: 1749.99,
    sale_price: 1549.99,
    rating: 4.7,
    reviews: 189,
    image: "https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=400&q=80",
    category: "Laptops",
    brand: "Dell",
    badge: "SALE",
    in_stock: true,
    is_featured: false,
  },
  {
    id: 4,
    name: "LG UltraWide 34\" Monitor",
    slug: "lg-ultrawide-34",
    price: 699.99,
    sale_price: 549.99,
    rating: 4.6,
    reviews: 301,
    image: "https://images.unsplash.com/photo-1527443224154-c4a573d3b9e5?w=400&q=80",
    category: "Monitors",
    brand: "LG",
    badge: "SALE",
    in_stock: true,
    is_featured: true,
  },
  {
    id: 5,
    name: "Logitech MX Keys S",
    slug: "logitech-mx-keys-s",
    price: 119.99,
    sale_price: null,
    rating: 4.5,
    reviews: 876,
    image: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=400&q=80",
    category: "Keyboards",
    brand: "Logitech",
    badge: null,
    in_stock: true,
    is_featured: false,
  },
  {
    id: 6,
    name: "Samsung 990 Pro 2TB SSD",
    slug: "samsung-990-pro-2tb",
    price: 179.99,
    sale_price: 149.99,
    rating: 4.9,
    reviews: 423,
    image: "https://images.unsplash.com/photo-1598452963314-b09f397a5c48?w=400&q=80",
    category: "Storage",
    brand: "Samsung",
    badge: "HOT",
    in_stock: true,
    is_featured: false,
  },
  {
    id: 7,
    name: "Razer BlackWidow V4 Pro",
    slug: "razer-blackwidow-v4",
    price: 229.99,
    sale_price: null,
    rating: 4.7,
    reviews: 145,
    image: "https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=400&q=80",
    category: "Gaming Gear",
    brand: "Razer",
    badge: "NEW",
    in_stock: false,
    is_featured: true,
  },
  {
    id: 8,
    name: "Corsair Dominator DDR5 32GB",
    slug: "corsair-dominator-ddr5",
    price: 219.99,
    sale_price: 189.99,
    rating: 4.8,
    reviews: 267,
    image: "https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?w=400&q=80",
    category: "Accessories",
    brand: "Corsair",
    badge: "SALE",
    in_stock: true,
    is_featured: false,
  },
];

export const mockBanners = [
  {
    id: 1,
    title: "Next-Gen Gaming Laptops",
    subtitle: "Unleash Maximum Performance",
    description: "Up to 40% off on top gaming laptops. Limited time offer!",
    image: "https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=1200&q=80",
    cta: "Shop Now",
    link: "/products?category=laptops",
    badge: "Limited Offer",
  },
  {
    id: 2,
    title: "Build Your Dream PC",
    subtitle: "Premium Components Await",
    description: "From GPUs to SSDs — everything you need to build the perfect rig.",
    image: "https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?w=1200&q=80",
    cta: "Explore Parts",
    link: "/products",
    badge: "New Arrivals",
  },
  {
    id: 3,
    title: "Pro Workstation Setup",
    subtitle: "Elevate Your Productivity",
    description: "Premium monitors, keyboards, and accessories for professionals.",
    image: "https://images.unsplash.com/photo-1527443224154-c4a573d3b9e5?w=1200&q=80",
    cta: "Shop Setup",
    link: "/products?category=monitors",
    badge: "Best Sellers",
  },
];

export const mockStats = {
  totalOrders: 1247,
  totalRevenue: 284650,
  totalProducts: 342,
  totalCustomers: 4821,
};
